include:
  - board: xiao_ble
    shield: lalapadmini_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: lalapadmini_left rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
